# Generated by Django 4.1 on 2022-09-20 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
            ],
        ),
        migrations.AddField(
            model_name='acomodacao',
            name='cliete',
            field=models.ManyToManyField(to='acomodacoes.cliente'),
        ),
    ]
