# Generated by Django 4.1 on 2022-09-20 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acomodacoes', '0004_tipoacomodacao_descricao_tipoacomodacao_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipoacomodacao',
            name='valor',
            field=models.FloatField(null=True),
        ),
    ]
